spring.application.name=auth-service
server.port=8081

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

# App Properties
app.jwtSecret=secretKeyRahatAliCognizantSecretKeyForAuthServices808756
app.jwtExpirationMs= 86400000

eureka.client.service-url.defaultZone=${EUREKA_SERVER}
eureka.client.register-with-eureka= true
eureka.client.fetch-registry: true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Optional: Customize OpenAPI docs path
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=DEBUG


spring.kafka.topic=user-profile

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.redis.host=redis-cache
spring.data.redis.port=6379